version: "2"

services:
  muchas:
    build: .
    environment:
    - NODE_ENV
    - DEBUG_PORT
    volumes:
      - ./:/app
    ports:
      - 6028:6028
    networks:
      - muchas
    command: npm run start:dev
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.7.1
    logging:
      driver: none
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - 9200:9200
    networks:
      - muchas
networks:
  muchas:
    driver: bridge